services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    restart: unless-stopped