spring:
  security:
    oauth2:
      client:
        registration:
          #          facebook:
          #          google:
          okta:
            client-id:
            client-secret:
            scope:
              - openid
              - profile
        provider:
          okta:
            issuer-uri: