server:
  port: 8087

spring:
  security:
    oauth2:
      client:
        registration:
          mywebclient:
            client-id: photo-app-webclient
            client-secret: 3717f1b4-654b-412a-b617-bdd2ef6fd221
            scope:
              - openid
              - profile
              - roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8087/login/oauth2/code/mywebclient
        provider:
          mywebclient:
            authorization-uri: http://localhost:8890/realms/appsdeveloperblog/protocol/openid-connect/auth
            token-uri: http://localhost:8890/realms/appsdeveloperblog/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8890/realms/appsdeveloperblog/protocol/openid-connect/certs
            user-info-uri: http://localhost:8890/realms/appsdeveloperblog/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username