server:
  port: 0

spring:
  application:
    name: demo-resource-server
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8890/realms/appsdeveloperblog/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}